services:
  sim:
    container_name: ibvs_sim
    image: ibvs_sim:latest
    build:
      context: ../..    
      dockerfile: project_files/docker_sim/Dockerfile
    stdin_open: true
    tty: true
    command: /bin/bash
    gpus: all
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=0
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../..:/root/ws_x500
